# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./EconomicEngineDebugGUI.h \
    ./qcustomplot.h
SOURCES += ./main.cpp \
    ./qcustomplot.cpp \
    c:/users/zecroque/source/repos/economicengine/economicenginedebuggui/economicenginedebuggui.cpp \
    c:/users/zecroque/source/repos/economicengine/economicenginedebuggui/main.cpp
FORMS += ./EconomicEngineDebugGUI.ui
RESOURCES += EconomicEngineDebugGUI.qrc
